spring.application.name=Spring
spring.datasource.url=jdbc:postgresql://localhost:5432/studentsexam
spring.datasource.username=postgres
spring.datasource.password=Yati@7457
spring.datasource.driver-class-name=org.postgresql.Driver
